# Generated by Django 3.1.7 on 2021-03-07 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('T', 'To Do'), ('I', 'In Progress'), ('P', 'Pending'), ('D', 'Done')], default='T', max_length=1),
        ),
    ]
